_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.8.13
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.8.13
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
